<?php
/** @var \Magebit\PageListWidget\Block\PageList $block */
/** @var \Magento\Framework\Escaper $escaper */

$Urls = $block->getSelectedPagesArray();
?>

<h2><?= $escaper->escapeHtml($block->getData('title')) ?></h2>
<ul>
    <?php foreach ($Urls as $url): ?>
        <li><a href=<?= $escaper->escapeHtml($url['value']) ?>><?=$escaper->escapeHtml($url['label'])?></a></li>
    <?php endforeach; ?>
</ul>
