<?php declare(strict_types = 1);

use Magebit\PageListWidget\Block\Widget\PageList;
use Magento\Framework\Escaper;

/** @var PageList $block */
/** @var Escaper $escaper */

$urls = $block->getSelectedPagesArray();
?>

<div>
    <h2><?= $escaper->escapeHtml($block->getData('title')) ?></h2>
    <ul>
        <?php foreach ($urls as $url): ?>
            <li><a href=<?= $escaper->escapeHtml($url['value']) ?>><?=$escaper->escapeHtml($url['label'])?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
