<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <div class="control" id="qty-counter" data-bind="scope: 'qty-counter'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <script type="text/x-magento-init">
                    {
                        "#qty-counter": {
                            "Magento_Ui/js/core/app": {
                               "components": {
                                    "qty-counter": {
                                        "component": "Magento_Catalog/js/qty-counter"

                }
            }
        }
    }
}
                </script>
                <img src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/checkmark.svg')?>" alt="CheckMark">
                <?php if ($block->displayProductStockStatus()) :?>
                    <?php if ($_product->isAvailable()) :?>
                        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php else :?>
    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
