<?php
use Magento\Framework\View\Element\Template;
use ModuleTest\FirstLayout\Block\Display;
use ModuleTest\FirstLayout\ViewModel\View;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var View $productData */


$productData = $block->getData("ViewModel");
$productName = $productData->getString();
?>
<h1>My First</h1>
<h2><?= $productName ?></h2>
<p>With Layout support</p>

